Week2
BertMoretz/GameRatings pull request #3
Opened 2019-02-08 11:39 UTC by BertMoretz

+webpack
+webpack-dev-server
+code transpiling

2019-02-08 11:48 UTC, kos33rd requested changes

2019-02-08 11:48 UTC, kos33rd commented on package.json
> +    "terser": "^3.14.1",
Возможно, лишняя зависимость. Для чего нужен этот пакет?

2019-02-08 11:58 UTC, BertMoretz commented on package.json
> +    "terser": "^3.14.1",
Без него вываливается **Terser TypeError: Cannot read property 'minify' of undefined**
Листая форумы, было два решения: откатить webpack до 4.20 или обновить terser до 3.14

2019-02-15 09:15 UTC, kos33rd commented on package.json
> +    "terser": "^3.14.1",
Окей, хорошо

2019-02-15 09:16 UTC, kos33rd approved these changes

2019-02-15 11:20 UTC, merged