Week3
BertMoretz/GameRatings pull request #4
Opened 2019-02-13 11:03 UTC by BertMoretz

+react support
+html webpack plugin

2019-02-15 09:18 UTC, kos33rd requested changes
Предлагаю перенести js-исходники в src. В остальном всё здорово.

2019-02-15 09:18 UTC, kos33rd commented on assets/js/index.js
> +ReactDOM.render( <h1>Hello by Albert!</h1>,
👍

2019-02-15 09:18 UTC, kos33rd commented on package.json
> +  "main": "./assets/js/index.js",
Я бы предложил хранить исходники в общепринятой директории `src`

2019-02-15 11:21 UTC, BertMoretz commented on package.json
> +  "main": "./assets/js/index.js",
Да, хорошо!

2019-02-15 11:29 UTC, BertMoretz commented on package.json
> +  "main": "./assets/js/index.js",
Сделано!

2019-02-21 20:34 UTC, kos33rd approved these changes

2019-02-21 20:37 UTC, merged