Week5
BertMoretz/GameRatings pull request #6
Opened 2019-03-01 11:03 UTC by BertMoretz

+ Routing
+ Design Improvements

2019-03-11 17:42 UTC, kos33rd requested changes
По заданию пятой недели нужно поправить 404 на странице деталей.
Также крайне рекомендую разложить компоненты и их стили в какую-то более наглядную структуру.

2019-03-11 17:42 UTC, kos33rd commented on src/details.css
> +.detailcard {
Исходные файлы больше 100 строк намекают на то, что хорошо бы что-нибудь декомпозировать.
Я предлагаю разбить все реакт-компоненты в директории js на "страницы" и "компоненты", разнеся их в соответствующие директории. Для каждой компоненты завести собственный .css-файл со стилями (если компоненте нужны стили).

2019-03-11 17:42 UTC, kos33rd commented on src/js/game-details.js
> +        const ratingClass = {
Инлайн-стилизацию стоит применять только в исключительных случаях - такой подход сложнее поддерживать и рефакторить. В данном кейсе я рекомендую вынести различные варианты оформления рейтинга в css-классы и в зависимости от условия навешивать на `<div/>` тот или иной класс.

2019-03-11 17:42 UTC, kos33rd commented on src/js/my-app-bar.js
> +            <img src={logo} class={style.logo}/>
Чтобы указать `class` в html мы должны передавать `className` в React.

2019-03-11 17:42 UTC, kos33rd commented on webpack.config.js
> +    historyApiFallback: true,
Если перейти на страницу деталей игры (например, http://localhost:9000/game/36950#) и нажать F5, то увидим белый экран и 404 в консоли.
Чтобы это поправить необходимо дополнительно прописать конфигурационную опцию `publicPath`.

2019-03-12 14:30 UTC, BertMoretz commented on webpack.config.js
> +    historyApiFallback: true,
Исправил основные замечания!

2019-03-12 14:32 UTC, BertMoretz commented on src/js/game-details.js
> +        const ratingClass = {
Эти изменения добавлю в ветку week6

2019-03-13 16:49 UTC, kos33rd approved these changes

2019-03-13 16:49 UTC, kos33rd commented on webpack.config.js
> +    historyApiFallback: true,
Отлично 👍
По 5 неделе апрув.

2019-03-13 17:52 UTC, merged