Week6
BertMoretz/GameRatings pull request #7
Opened 2019-03-08 11:12 UTC by BertMoretz

+ added routing

2019-03-11 17:52 UTC, kos33rd requested changes
По заданию шестой недели нужно закончить с пробросом BACKEND_URL в URL, по которому axios будет забирать данные. 
В остальном всё круто.

2019-03-11 17:52 UTC, kos33rd commented on package.json
> +    "dev:stub": "cross-env PORT=1234 BACKEND_URL=/ npm run start:dev",
Этот параметр необходимо во-первых пробросить в код с помощью webpack-плагина. Во-вторых этот параметр необходимо учитывать при построении URL при вызове axios.

Как это сделать можно подсмотреть в репозитории нашего проекта:
https://github.com/kos33rd/web-developer-course-spring-2019/commit/21ab5d704eb6d2ba4ab717bfa9869082f153e9fe

2019-03-11 17:52 UTC, kos33rd commented on stub/server.js
> +        if (port === '1234') {
Немного непонятна конструкция с выбором того или иного файла в зависимости от порта. Как вижу, файла `games1.json` всё равно не существует в репозитории.

2019-03-11 17:52 UTC, kos33rd commented on webpack.config.js
>    //mode: 'development',
Эту директиву можно передавать через CLI в момент запуска `webpack-dev-server` в секции scripts в package.json:
```json
    "start:dev": "webpack-dev-server --mode development",
```

2019-03-12 15:20 UTC, BertMoretz commented on stub/server.js
> +        if (port === '1234') {
Я делал по примеру вашего репозитория. Там просто тоже character1 отсутствует.

2019-03-12 15:25 UTC, BertMoretz commented on package.json
> +    "dev:stub": "cross-env PORT=1234 BACKEND_URL=/ npm run start:dev",
Сделал

2019-03-13 16:52 UTC, kos33rd commented on stub/server.js
> +        if (port === '1234') {
Копипаста - не всегда хорошее решение. В нашем репо это был пример возможного расширения возможностей кастомизировать поведение приложения в dev-окружении. Не обязательно было это копировать.

2019-03-13 16:56 UTC, kos33rd commented on package.json
> +    "dev:stub": "cross-env PORT=1234 BACKEND_URL=/ npm run start:dev",
По второй части - обращению к разным бэкэндам - так пока что ничего и не вижу. 
Ради этой возможности мы и затевали всё это задание же

2019-03-13 16:57 UTC, kos33rd requested changes
Жду работы с разными бэкэндами с учетом передаваемого в js `BACKEND_URL`.

2019-03-13 18:44 UTC, BertMoretz commented on package.json
> +    "dev:stub": "cross-env PORT=1234 BACKEND_URL=/ npm run start:dev",
Я понял, что надо было сделать. Теперь при вызове **dev:stub** данные берутся из локального json файла, а при **dev:api** - из api.

2019-03-13 21:03 UTC, kos33rd approved these changes
👌 апрув

2019-03-13 21:39 UTC, merged