+ added redux
BertMoretz/GameRatings pull request #8
Opened 2019-03-27 14:42 UTC by BertMoretz

2019-03-31 20:57 UTC, kos33rd requested changes
Предлагаю доработать кейс с ошибкой при получении данных с бэкэнда.

2019-03-31 20:57 UTC, kos33rd commented on src/redux/reducers/index.js
> +    console.log('Reducer called with action', action);
Эту отладочную информацию можно не выводить - мы подключили redux dev tools, которые дают больше деталей о происходящем.

2019-03-31 20:57 UTC, kos33rd commented on src/pages/home/home-page.js
> +                //this.props.gamesListLoadFailed()
Почему закомментировано?

2019-04-01 08:52 UTC, BertMoretz commented on src/pages/home/home-page.js
> +                //this.props.gamesListLoadFailed()
У меня выводило ошибку почему-то. Потом я нашел ошибку, она в другом была. А раскомментить забыл (:

2019-04-02 11:20 UTC, BertMoretz commented on src/pages/home/home-page.js
> +                //this.props.gamesListLoadFailed()
Сделано (:

2019-04-05 13:41 UTC, kos33rd approved these changes

2019-04-06 08:23 UTC, merged